version: 2
project_name: ambient-weather-fusion
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
        goarm: 7
archives:
  - formats: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
  groups:
    - title: Features
      order: 0
      regexp: "(feat)"
    - title: Fixes
      order: 1
      regexp: "(fix|perf)"
    - title: Dependencies
      order: 999
      regexp: "\\(deps\\):"
    - title: Others
      order: 998
dockers_v2:
  - dockerfile: goreleaser.Dockerfile
    images:
      - ghcr.io/gabe565/{{ .ProjectName }}
    tags:
      - latest
      - "{{ .Version }}"
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
    platforms:
      - linux/amd64
      - linux/arm/v7
      - linux/arm64
